cloneable_entities:
  - block
  - block_content
  - block_content_type
  - block_visibility_group
  - collection_type
  - collection
  - collection_item
  - collection_item_type
  - config_split
  - crop
  - crop_type
  - editor
  - entity_browser
  - field_config
  - field_storage_config
  - file
  - filter_format
  - section_import_mapped_object
  - class_session
  - image_style
  - key
  - key_config_override
  - linkit_profile
  - media_type
  - media
  - pdf_image_entity
  - metatag_defaults
  - migration_group
  - migration
  - node_type
  - node
  - path_alias
  - persona
  - persona_type
  - person
  - redirect
  - salesforce_auth
  - salesforce_mapping
  - salesforce_mapped_object
  - search_api_server
  - search_api_index
  - search_api_task
  - action
  - menu
  - taxonomy_term
  - taxonomy_vocabulary
  - user
  - user_role
  - view
  - webform
  - webform_submission
  - webform_options
  - menu_link_content
  - pathauto_pattern
  - paragraph
  - paragraphs_type
  - date_format
  - entity_form_mode
  - entity_view_display
  - entity_form_display
  - entity_view_mode
  - base_field_override
  - facets_facet
  - facets_facet_source
  - facets_summary
  - ilr_employee_position
  - configurable_language
  - language_content_settings
  - paragraphs_browser_type
