_core:
  default_config_hash: CQLKbL2AgHGqE2ilC8yF4Mhg142d5_lgO6nJF7Ws66w
hotlink: false
origin: 'https://www.ilr.cornell.edu'
origin_dir: sites/default/files-d8
proxy_headers: ''
use_imagecache_root: true
verify: true
excluded_extensions: ''
